export const CartActionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    ADD_QUANTITY: 'ADD_QUANTITY',
    REMOVE_QUANTITY: 'REMOVE_QUANTITY',
    CLEAR_CART: 'CLEAR_CART'
}