export const ProductActionTypes = {
    GET_ALL_PRODUCTS_START: 'GET_ALL_PRODUCTS_START',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_ERROR: 'GET_ALL_PRODUCTS_ERROR'
}