export const UserActionTypes = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_ERROR: 'EMAIL_SIGN_IN_ERROR',
    CHECK_FOR_USER_AUTH: 'CHECK_FOR_USER_AUTH',
    PLACE_AN_ORDER_START: 'PLACE_AN_ORDER_START',
    PLACE_AN_ORDER_SUCCESS: 'PLACE_AN_ORDER_SUCCESS',
    PLACE_AN_ORDER_ERROR: 'PLACE_AN_ORDER_ERROR',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_ERROR: 'SIGN_OUT_ERROR'
}